name: "Tsun Gen3 Proxy"
version: "1.0.0"
slug: "tsun_gen3_proxy"
description: "Addon Home Assistant pour le proxy Tsun Gen3"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
options: {}
schema: {}
