name: "Tsun Gen3 Proxy"
version: "1.0.0"
slug: "tsun_gen3_proxy"
description: "Proxy MQTT pour onduleur Tsun Gen3"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "homeassistant"
  mqtt_password: "password"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
